name: "Accessibility Check"

on: 
  workflow_call

jobs: 
  a11y-check:
    runs-on: self-hosted

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          cache: 'npm'
          node-version-file: '.nvmrc' 
          # node-version: 20 ## Using a .nvmrc file to stay in sync with the repo

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Run pa11y
        run: npm run pa11y "--sitemap https://dyx9tyg1h7v8p.cloudfront.net/${{github.event.number}}/sitemap.xml --sitemap-exclude /*.pdf  --sitemap-find https://ab2d.cms.gov/ --sitemap-replace https://dyx9tyg1h7v8p.cloudfront.net/ --json > pa11y-results.json"
  
      - name: Save Report to Action Summary
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const results = "pa11y-results.json"
            const data = JSON.parse(fs.readFileSync(results, "utf-8"))

            let body = "## Accessibility Report \n\n";
            body += "| URL | Errors |\n";
            body += "| --- | ------ |\n";

            Object.entries(data.results).forEach(([url, issues]) => {
              body += `| ${url} | ${issues.length} errors |\n`;
            });

            core.summary.addRaw(body).write();