name: "Broken Link Check"

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_call:
  workflow_dispatch:

jobs:
  broken-link-check:
    runs-on: codebuild-ab2d-website-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Check for broken links"
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          jobSummary: true
          fail: true
          args: --no-progress --accept '200..=299, 401, 403, 405' ~/_[pages,layouts,includes,data]/**.[md,html,yml]
