name: "Broken Link Check"

on:
  push: #FIXME
  workflow_call:
  workflow_dispatch:

jobs:
  broken-link-check:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Check for broken links"
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          jobSummary: true
          fail: true
          args: --no-progress --accept '200..=299, 401, 403, 405' ~/_[pages,layouts,includes]/**.[md,html]
