name: "Broken Link Check"

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0 # Every Sunday at midnight

jobs:
  broken-link-check:
    runs-on: codebuild-ab2d-website-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
          # node-version: 20 ## Using a .nvmrc file to stay in sync with the repo

      - name: Install jekyll and bundler
        run: |
          gem install bundler
          bundle install

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Compile assets with Gulp
        run: |
          npm run assets:build

      - name: Build the site
        run: |
          bundle exec jekyll build

      - name: "Check for broken links"
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          jobSummary: true
          args: --base https://ab2d.cms.gov --no-progress --accept '200..=299, 401, 403, 405' ./_site/**/*.html
