name: "deploy"

on:
  push: #FIXME
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-dev:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    # FIXME
    # if: ${{ !startsWith(github.actor, 'bot-') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install ruby and bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build the site
        env:
          JEKYLL_ENV: "production"
        run: |
          npm ci
          npm run assets:build
          bundle exec jekyll build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.NON_PROD_ACCOUNT }}:role/delegatedadmin/developer/ab2d-test-github-actions

      - name: Fetch Parameters
        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        with:
          params: |
            CLOUDFRONT_BUCKET=/ab2d/test/web/nonsensitive/s3-bucket

      - name: Deploy the site
        run: |
          aws s3 sync --delete _site/ "s3://${CLOUDFRONT_BUCKET}/"
