name: "deploy"

on:
  push:
  workflow_dispatch:
    inputs:
      deploy_path:
        description: "S3 directory deployment location"
        default: "main"
  workflow_call:
    inputs:
      deploy_path:
        required: false
        type: string

jobs:
  deploy-dev:
    permissions:
      contents: read
      id-token: write
    runs-on:
      - codebuild-ab2d-website-${{ github.run_id }}-${{ github.run_attempt }}
    # FIXME
    # if: ${{ !startsWith(github.actor, 'bot-') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install ruby and bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Compile assets with Gulp
        run: |
          npm run assets:build

      - name: Build the site
        env:
          JEKYLL_ENV: "production"
        run: |
          bundle exec jekyll build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.NON_PROD_ACCOUNT }}:role/delegatedadmin/developer/ab2d-test-github-actions

      - name: Deploy the site
        run: |
          aws s3 sync --delete _site/ s3://ab2d-test-website20250610200200374300000001/
