name: push to dev

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{  github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    with:
      deploy_path: "main"
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  a11y-check:
    needs: deploy
    uses: ./.github/workflows/a11y-check.yml
