name: push to dev

on: 
  push:
    branches:
      - uswds-redesign

jobs: 
  deploy: 
    with:
      deploy_path: "uswds-redesign"
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  a11y-check:
    needs: deploy
    uses: ./.github/workflows/a11y-check.yml
    
  # broken-link-check:
  #   uses: ./.github/workflows/broken-link-check.yml