name: release

on:
  release:
    types: ['released']

jobs:
  deploy:
    with:
      deploy_path: "main"
    uses: ./.github/workflows/promote.yml
    permissions:
      id-token: write
    secrets: inherit
